name: CI

on:
  push:
    branches: [ "main", "develop" ]

permissions:
  contents: read
  packages: write

jobs:
  build-test-and-push-image:
    runs-on: ubuntu-latest

    steps:
      # 1) Kodu Ã§ek
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Java 21
      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      # 3) Test & Build
      - name: Build & Test
        run: ./mvnw clean verify

      # 4) GHCR Login (username: actor, password: GITHUB_TOKEN)
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 5) Docker Build & Push (SHA + latest)
      - name: Build and push Docker image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}/order-service
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest .
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest
